name: API Build
on:
  push:
    paths:
      - "api/**"
      - ".github/workflows/api-build.yml"
  workflow_dispatch:

jobs:
  build:
    name: Build API
    runs-on: ubuntu-latest
    steps:
        - uses: checkout@v4
        - run: dotnet --list-runtimes
        - run: dotnet --list-sdks
        - run: dotnet build
          working-directory: api